highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://rasserr.github.io
author: FÃ¡bio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ""
title: "Rasser"
name: Gwak Junbeom
email: Email
email_full: mailto:junbeomkwak@gmail.com
website: Blog
website_full: https://rasser.kr/
github: rasserr
twitter: Rasser_pwn
tel: +82 10-9771-0923
tel_full: tel:+821097710923
google_maps: ''
address:
  street: Seoul
  postcode: 31337
  city: Seoul
  country: South Korea
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
